### ISSUE TITLE
Bouwen: Fonts & Custom properties toevoegen

### ISSUE THREAD

**Issue by Annevd** [Annevd/your-tribe-for-life-profile-card#15]

**Comment by Annevd** [comment]
## 11-9 Fonts & Custom properties

In de static folder van mijn repo heb ik een folder aangemaakt met daarin custom fonts die ik ga gebruiken. Deze spreek ik in de CSS aan met `@font-face`.

**Custom font:**

![Image](https://github.com/user-attachments/assets/7c8a8900-07da-48f8-8282-94057b1df1e3)

Uiteraard heb ik ook alvast een aantal custom properties aangemaakt voor bijvoorbeeld de kleuren.

**Custom properties:**

```CSS
:root {
    --background-card: #F4EFEA;
    --accent-color-1: #D8A06C;
    --accent-color-2: #73AFDB;
    --accent-color-3: #B478A1;
    --text-color: #4D382C;
}
```
