### ISSUE TITLE
Bouwen: CSS Noise filter

### ISSUE THREAD

**Issue by Annevd** [Annevd/your-tribe-for-life-profile-card#16]

**Comment by Annevd** [comment]
## 12-9 Noise filter

Ik heb een noise filter toegevoegd door een png met de noise textuur met een `::before` op de `<body>`  als `background-image` te zetten met een opacity van `0.05`.

```CSS
body::before {
    content: "";
    position: fixed;
    inset: 0;
    z-index: 9999;
    background-image: url("../images/seamless-noise-texture.jpg");
    opacity: 0.05;
    pointer-events: none;
}
```

**Dit is het resultaat tot nu toe:**

![Image](https://github.com/user-attachments/assets/f45e14f3-2fe8-4d6f-b0ad-8325ed41aa96)
