### ISSUE TITLE
Animatie sterretjes mobiel scherm

### ISSUE THREAD

**Issue by Annevd** [Annevd/your-tribe-for-life-profile-card#30]

**Comment by Annevd** [comment]
## 18-9 Star animation mobile

Om het voor mobile nog steeds interessant te maken heb ik nog een animatie gemaakt voor de sterren. Deze animeren van links naar rechts infinitely.

```CSS
.sparkle {
    animation: sparkle 0.4s infinite;
}

@keyframes sparkle {
    25% {
        transform: rotate(3deg);
    }

    75% {
        transform: rotate(-3deg);
    }
}
```
