### ISSUE TITLE
dark mode custom properties maken

### ISSUE THREAD

**Issue by Annevd** [Annevd/your-tribe-for-life-profile-card#32]

**Comment by Annevd** [comment]
## 19-9 Added custom properties for dark mode

```CSS
body.dark-mode {
    --page-background-color: #0C1422;
    --background-card: #1F2639;
    --accent-color-1: #CC3E86;
    --accent-color-2: #ffe189;
    --accent-color-3: #747ec2;
    --text-color: #A2DFCE;
    --star-color: #ffe189;
}
```

[commit](https://github.com/Annevd/your-tribe-for-life-profile-card/commit/bde6118a25c4e1ded1ab3709a90578fb0838679e)
