### ISSUE TITLE
Bouwen: CSS

### ISSUE THREAD

**Issue by Annevd** [Annevd/your-tribe-for-life-profile-card#7]

**Comment by Annevd** [comment]
## 10-9 Basic CSS

Ik ben begonnen met het klaarzetten van de belangrijkste CSS, zoals het grid waarin ik op een speelse manier mijn elementen kan neerzetten. Dit heb ik gedaan door 3 kolommen te maken en 6 rijen, aan de hand van het voorbeeld in mijn breakdown en Figma design.

Vervolgens plaats ik elk individueel element op de juiste plek met `grid-column: ...` en `grid-row: ...`.

**CSS Grid:**
```CSS
article {
    display: grid;
    grid-template-columns: repeat(3, auto) ;
    grid-template-rows: repeat(6, auto) ;
    max-width: 18rem;
    grid-gap: 1rem;
    padding: 1rem;
}

h1 {
    grid-column: 1/3;
    grid-row:1; 
}

.links {
    grid-column: 2/4;
    grid-row: 1;
}

.bio {
    grid-column: 2/4;
    grid-row: 2;
}

.info {
    grid-column: 1;
    grid-row: 5;
}

div {
    grid-column: 1/4;
    grid-row: 3/5;
}

.orbit-icon {
    grid-column: 1;
    grid-row: 2;
}

.selfie {
    grid-column: 2/4;
    grid-row: 3/7;
}

p:last-of-type {
    grid-column: 2/4;
    grid-row: 6;
}
```

**Dit is het resultaat tot nu toe:**

![Image](https://github.com/user-attachments/assets/f7ebab01-be43-4d2e-aafc-bd405d2231f6)

**Comment by Annevd** [comment]
## 11-9 Detailed CSS

Vandaag ben ik bezig geweest met typografie zoals fonts, font sizing en font styling. Ook heb ik alles de kleuren gegeven vanuit mijn design aan de hand van custom properties. Ook heb ik nog wat tweaks gedaan aan de responsiveness van het kaartje aan de hand van media queries zodat het op minimaal 320px er ook nog goed uit ziet.

**Dit is het resultaat tot nu toe:**

![Image](https://github.com/user-attachments/assets/88eea1c2-b219-42d9-aa30-6530263fdbae)

**Comment by Annevd** [comment]
## 12-9 Star SVG's & Noise filter

Door het kaartje op `position: relative`  te zetten kon ik de ster svg's met `position: absolute;` op de gewenste positie plaatsen in mijn kaartje.

Ook heb ik een noise filter toegevoegd door een png met de noise textuur met een `::before` op de `<body>`  als `background-image` te zetten met een opacity van `0.05`.

```CSS
body::before {
    content: "";
    position: fixed;
    inset: 0;
    z-index: 9999;
    background-image: url("../images/seamless-noise-texture.jpg");
    opacity: 0.05;
    pointer-events: none;
}
```

**Dit is het resultaat tot nu toe:**

![Image](https://github.com/user-attachments/assets/f45e14f3-2fe8-4d6f-b0ad-8325ed41aa96)
