### ISSUE TITLE
Bouwen: Sterretjes animatie

### ISSUE THREAD

**Issue by Annevd** [Annevd/your-tribe-for-life-profile-card#8]

**Comment by Annevd** [comment]
## 12-9 Orbit animation

Ik ben vandaag begonnen met het proberen te maken van de orbit animatie.
Als eerste probeerde ik aan de hand van [deze](https://codepen.io/mikeK/pen/gyYWEe) [twee](https://codepen.io/rounabhsahu/pen/MWPgXJw?editors=1100) voorbeelden de animatie toe te passen op mijn visitekaartje maar daar liept ik vast. Ik heb toen met wat [hulp van Sanne](https://codepen.io/Annevd/pen/zYVXrVj) mijn idee half werkend gekregen:

![Image](https://github.com/user-attachments/assets/dc380d15-b0f4-437f-8061-1eefffc564fa)

Zoals te zien werkt de animatie nog niet op de bovenste ring. Dit moet ik nog uitzoeken.

**De code zit als volgt in elkaar:**

De 2 ster svg's zitten in een div, deze div is voor de orbit ringen die je ziet, die zich weer in het kaartje bevindt.

```SVELTE
<article>
    <!-- content here -->
          <div class="orbit">
                <svg class="sparkle left" width="44" height="86" viewBox="0 0 177 347" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M89 0c0 141 19 179 86 179-73 1-86 46-86 166-1-135-23-165-89-166 79 1 88-54 89-179Z" fill="#000"/>
                    <path d="M89 0c0 142 19 180 88 179-75 0-89 46-88 168 0-137-23-167-89-168 79 1 88-54 89-179Z"/>
                </svg>
            </div>

            <div class="orbit">
                <svg class="sparkle right" width="44" height="86" viewBox="0 0 177 347" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M89 0c0 141 19 179 86 179-73 1-86 46-86 166-1-135-23-165-89-166 79 1 88-54 89-179Z" fill="#000"/>
                    <path d="M89 0c0 142 19 180 88 179-75 0-89 46-88 168 0-137-23-167-89-168 79 1 88-54 89-179Z"/>
                </svg>
            </div>
<article>
```

Met custom properties wordt er precies berekend afhankelijk van deze waardes hoeveel witruimte, kanteling, etc. moet zijn.

```CSS
article {
        --width-card: 22rem;
        --orbit-whitespace:calc(var(--width-card) * .1);
	--orbit-diameter:calc( var(--width-card) + var(--orbit-whitespace) * 2 );
	--orbit-radius:calc( var(--width-card) * .5 + var(--orbit-whitespace) );
	--orbit-offset-y:calc(var(--width-card) * .5);
	--orbit-tilt-y:-20deg;
	--orbit-tilt-x:80deg;
	
	--width-star:calc(var(--width-card) * .25);
    width:var(--width-card);
	/* aspect-ratio:3/5; */
	
    --width-star:calc(var(--width-card) * .25);
	
	transform-style:preserve-3d;
}
```

Orbit is de ring die om het kaartje heen gaat:

```CSS
.orbit {
	position:absolute;
        left: -2.25rem;
	width:var(--orbit-diameter);
	aspect-ratio:1/1;
	border:solid .2em var(--text-color);
	border-radius:50%;
        margin: 0;
	
	display:grid;
	place-items:center;
	
	transform-style:preserve-3d;
	transform:
		translateY( var(--ty, 0) )
    /* als je perspectief wilt voor de orbits	- optie 1	*/
/* 		perspective(160vw) */
		rotateX( var(--orbit-tilt-x) )
		rotateY( var(--orbit-tilt-y) )
		;
}

.orbit:nth-of-type(1) {
	--ty:calc(var(--orbit-offset-y) * -1); /* Dit zorgt ervoor dat de 2 ringen verticaal uit elkaar gaan staan */
}

.orbit:nth-of-type(2) {
	--ty:calc(var(--orbit-offset-y) * 1);
}
```

De ster krijgt hier de keyframe animation toegepast en hoe snel elke ster moet gaan:

```CSS
.sparkle {
    position: unset;
    width:var(--width-star);

    animation: star linear var(--orbit-time) infinite;
}


.orbit:nth-of-type(1) .sparkle {
	--orbit-time:5s;
}

.orbit:nth-of-type(2) .sparkle {
	--orbit-time:4s;
}

@keyframes star {
	0% {
		transform:
			/* als je perspectief wilt voor de orbits	- optie 2	*/
/* 			perspective(160vw) */
			rotateZ(0turn)
			rotateX(90deg)
			translateZ( calc( var(--orbit-radius) * -1) )
			rotateY(0turn)
      /* compenseren voor tilt van orbit */
			rotateZ( var(--orbit-tilt-y) )
			rotateX( calc(270deg - var(--orbit-tilt-x)))
		;
	}
	
	100% {
		transform:
			/* als je perspectief wilt voor de orbits	- optie 2	*/
/* 			perspective(160vw) */
			rotateZ(1turn)
			rotateX(90deg)
			translateZ( calc( var(--orbit-radius) * -1) )
			rotateY(-1turn)
			/* compenseren voor tilt van orbit */
			rotateZ( var(--orbit-tilt-y) )
			rotateX( calc(270deg - var(--orbit-tilt-x)))
		;
	}
}

}

```
